apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "fingateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fingateway.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fingateway.labels" . | nindent 8 }}
    spec:
      containers:
      - name: fingateway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: FMP_API_KEY
          valueFrom:
            secretKeyRef:
              name: fingateway-secrets
              key: fmp-api-key
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5